version: '3.8'
services:
  app:
    container_name: mybb-chrono-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/${DB_NAME}
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    container_name: mybb_chrono_mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mybb_chrono_boards:/data/mybb_chrono_boards

volumes:
  mongodb-data:
